### PR TITLE
Block interface refinement

### PR DESCRIPTION
**Pull request by jklmnn**
- finish implementation of linux and muen
 - separate tests for linux, muen and genode
 - improved request handling

### CODE REVIEW

**Comment by jklmnn** [comment]
We still don't have a distinction between temporary and permanent errors (especially in regards to the request allocation). I this is important to prevent applications from retrying unsupported requests indefinitely. Maybe we could also remove the maximum transfer size function then (which isn't supported by any of our platforms anyway) and incorporate this property into the permanent request semantic.

**Comment by senier** [comment]
> We still don't have a distinction between temporary and permanent errors (especially in regards to the request allocation). I this is important to prevent applications from retrying unsupported requests indefinitely. Maybe we could also remove the maximum transfer size function then (which isn't supported by any of our platforms anyway) and incorporate this property into the permanent request semantic.

I don't see any issue for this topic, please create one. Is it helpful to address this within 1.1?

I'm not sure about the maximum transfer size topic. How would an application find the maximum size of a request? Just try and see whether a permanent error occurs (which could have other reasons)? Or don't application need to know the request size (dynamically) and just chose a size that is supposed to work on all supported platforms?

**Comment by jklmnn** [comment]
> I don't see any issue for this topic, please create one. Is it helpful to address this within 1.1?

I think we should address is in 1.1. None of our current component will be able to determine if the request will eventually work so they all will endlessly loop and try to insert a request that is never going to work.

**Comment by jklmnn** [comment]
I created a separate issue: https://github.com/Componolit/ada-interfaces/issues/78.

**Pull request merged**
